[package]
name = "qemu-riscv"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
ns16550a = "0.1.0"
riscv = "0.10.0"
log = { path = "../../../lib/log" }
spin = "0.9"
embedded-hal = "=1.0.0-alpha.9"
embedded-hal-nb = "=1.0.0-alpha.1"
